language: ruby
rvm:
  - 2.5.1
sudo: required
addons:
  chrome: stable
jdk:
  - oraclejdk8
  
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
