language: ruby
rvm:
  - '2.3.4'
sudo: false
addons:
  chrome: stable
jdk:
  - oraclejdk8
  
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
